### ISSUE TITLE
Missing pretrained model

### ISSUE THREAD

**Issue by gomax22** [NimSed/stellar-karaoke#1]
Dears,

I'm a M. Sc. in Applied CS (Machine Learning & Big Data) student. Actually, I'm involved in a particular project related to the characterisation of exoplanets' atmosphere using deep learning. Searching through the literature, I've found your paper and this interesting repository. I would like to repeat the experiment, at least, starting from the pretrained model.
Unfortunately, the link reported in model/fetch_model.sh is down.
I've noted also that training script is missing.

So, waiting for your reply and missing elements,
Best Regards,
Massimiliano Giordano Orsini

**Comment by NimSed** [comment]
Hi and thanks for your interest in the work!

The link to the pretrained model is updated and should be working now -- please let me know if you still have issues with it. Please note that before you can start playing with the model you are going to need to have sample fits files too -- to be stored in {root_dir}/fits. One easy way of obtaining them is through the [ESO Science Portal](https://archive.eso.org/scienceportal/).

The training script needs to be cleaned up before it can be uploaded. Please stay tuned -- and keep poking us if it doesn't appear in the repository soon!

**Comment by NimSed** [comment]
@gomax22, please let me know if the above addressed this issue, so I can proceed and close it.
